name: distribution_shift_perception
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _x86_64-microarch-level=3
  - absl-py=2.3.1
  - alsa-lib=1.2.14
  - astunparse=1.6.3
  - blas=1.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - contourpy=1.3.2
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.6
  - double-conversion=3.3.1
  - expat=2.7.3
  - flatbuffers=25.2.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - gast=0.6.0
  - giflib=5.2.2
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.73.1
  - h2=4.3.0
  - h5py=3.15.1
  - harfbuzz=11.0.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - keras=3.12.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libclang-cpp20.1=20.1.8
  - libclang13=21.1.0
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.4.1.4
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurl=8.17.0
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libml_dtypes-headers=0.5.3
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libntlm=1.8
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.7
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtensorflow_cc=2.19.1
  - libtensorflow_framework=2.19.1
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mdurl=0.1.2
  - ml_dtypes=0.5.1
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - namex=0.1.0
  - nccl=2.28.9.1
  - ncurses=6.5
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - optree=0.17.0
  - packaging=25.0
  - pcre2=10.44
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - protobuf=6.31.1
  - pthread-stubs=0.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.9.23
  - python_abi=3.10
  - qhull=2020.2
  - qt6-main=6.9.0
  - re2=2025.11.05
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.19.1
  - tensorflow-base=2.19.1
  - tensorflow-estimator=2.19.1
  - termcolor=3.2.0
  - tk=8.6.15
  - tornado=6.5.2
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wayland=1.23.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=2.0.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - black==25.11.0
      - click==8.3.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - pathspec==0.12.1
      - platformdirs==4.5.0
      - pytokens==0.3.0
      - scipy==1.15.3
      - sympy==1.14.0
      - tomli==2.3.0
      - torch==2.9.1+cu126
      - torch-two-sample==0.1
      - torchvision==0.24.1+cu126
      - triton==3.5.1
